### ISSUE TITLE
Protocol "https" not supported or disabled in libcurl

### ISSUE THREAD

**Issue by amirsaeidy** [deepmind/spiral#1]
after runnig the following code :
```python3 setup.py develop --user```
this error appears :
```
CMake Error at libmypaint-stamp/download-libmypaint.cmake:159 (message):
  Each download failed!

    error: downloading 'https://github.com/mypaint/libmypaint/releases/download/v1.3.0/libmypaint-1.3.0.tar.xz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1



         --- LOG END ---
```

I'm using ubuntu 18 and this is curl version :

```
curl 7.65.3 (x86_64-pc-linux-gnu) libcurl/7.65.3 OpenSSL/1.1.1
Release-Date: 2019-07-19
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS HTTPS-proxy IPv6 Largefile NTLM NTLM_WB SSL TLS-SRP UnixSockets
```

**Comment by ddtm** [comment]
It doesn't seem like a problem specific to this project. Not sure what causes it but I would suggest downloading the archive manually (https://github.com/mypaint/libmypaint/releases/download/v1.3.0/libmypaint-1.3.0.tar.xz) and patching `CMakeLists.txt` to use local file URL (see https://github.com/deepmind/spiral/blob/master/CMakeLists.txt#L26)

**Comment by ddtm** [comment]
I added a link to a pre-build Docker image to README. Please use this if my suggestion above didn't help.
